# Generated by Django 5.0.2 on 2024-02-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "root_url",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="root_url",
                        to="url.urlmodel",
                    ),
                ),
                (
                    "sitemap_url",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sitemap_url",
                        to="url.urlmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Website",
                "verbose_name_plural": "Websites",
                "db_table": "core_websites",
            },
        ),
    ]
