# Generated by Django 5.0.2 on 2024-02-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrlInventoryReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status_code", models.IntegerField()),
                (
                    "page_content_file",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectmodel",
                    ),
                ),
                (
                    "request_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_url",
                        to="url.urlmodel",
                    ),
                ),
                (
                    "response_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_url",
                        to="url.urlmodel",
                    ),
                ),
            ],
            options={
                "db_table": "report_raw_page_data",
                "unique_together": {("project", "request_url")},
            },
        ),
    ]
