# Generated by Django 5.0.2 on 2024-02-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("topic", "0001_initial"),
        ("url", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergingQueryReportModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impressions_last_week", models.IntegerField(blank=True, null=True)),
                ("clicks_last_week", models.IntegerField(blank=True, null=True)),
                (
                    "ctr_last_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "position_last_week",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("impressions_last_month", models.IntegerField(blank=True, null=True)),
                ("clicks_last_month", models.IntegerField(blank=True, null=True)),
                (
                    "ctr_last_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "position_last_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("from_last_week", models.BooleanField(default=False)),
                ("from_last_month", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.projectmodel",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="topic.topicmodel",
                    ),
                ),
                (
                    "url_last_month",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_query_last_month",
                        to="url.urlmodel",
                    ),
                ),
                (
                    "url_last_week",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_query_last_week",
                        to="url.urlmodel",
                    ),
                ),
            ],
            options={
                "db_table": "report_emerging_query",
            },
        ),
    ]
